### PR TITLE
feat: monorepo layout and scripts

### PR DESCRIPTION
**Pull request by ivelin**
WIP for #2

### CODE REVIEW

**Comment by ivelin** [comment]
@nerderlyne is this going in the right direction? I've started by reusing best practices from the sweat-token repo.

**Comment by nerderlyne** [comment]
hey this looks great @ivelin 
lmk when you're ready to merge this so we can port over existing repos! 

for reference these are currently active repos related to wrappr - 
- https://github.com/kalidao/wrappr-ui (ui)
- https://github.com/kalidao/wrappr-subgraph (subgraph)
- https://github.com/kalidao/wrappr-docs (docs + guide)

**Comment by ivelin** [comment]
@nerderlyne I resolved the merge conflicts and fixed startup scripts. I think it's ready to merge.

**Comment by z0r0z** [comment]
very nice @ivelin !

**Pull request merged**
